# docker-compose version
version: "3.8"

volumes: 
  database_data_volumes: {}

# docker-compose config
services:
  mysql:
    image: mysql:8.0
    command: # pre command
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${DB_TZ}
    ports: # container external:internal port
      - ${DB_PORT}:3306 
    volumes:
      - database_data_volumes:/var/lib/mysql
