# docker-compose version
version: "3.8"

# docker-compose config
services:
  mysql_database:
    image: mysql:8.0
    restart: always
    command: # pre command
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    environment: 
      - MYSQL_USER=root
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${DB_TZ}
    ports: # container external:internal port
      - ${DB_PORT}:3306 
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql:cached